### ISSUE TITLE
Cannot Interpret result of bff deduplication

### ISSUE THREAD

**Issue by ethany21** [mlfoundations/dclm#80] opened 2024-09-20 12:22 UTC
I am using bff to deduplicate documents or duplicated substring within document(s)

I have jsonl files like

1. test_1.jsonl
```
{"text": "hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david"}
{"text": "hello world my name is elastic david i am data system engineer want to build real time olap materialized view"}
```

2. test_2.jsonl
```
{"text": "hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david"}
{"text": "hello world my name is elastic david i am data system engineer want to build real time olap materialized view"}
{"text": "hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david"}
```

And I ran command like

```
cargo run --release bff   
 --inputs ./input/test   
 --output-directory ./output/    
 --expected-ngram-count 100    
 --fp-rate 0.01    
 --min-ngram-size 2    
 --max-ngram-size 50    
 --filtering-threshold 0.8    
 --remove-type document

```

And generated two jsonl files within ./output/ directory are like

1. test_1.jsonl
```
{"bff_contained_ngram_count":1,"bff_duplicate_spans":[[0,184]],"text":"hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david"}
{"bff_contained_ngram_count":1,"bff_duplicate_spans":[[0,109]],"text":"hello world my name is elastic david i am data system engineer want to build real time olap materialized view"}

```

2. test_2.jsonl

```
{"bff_contained_ngram_count":0,"bff_duplicate_spans":[],"text":"hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david"}
{"bff_contained_ngram_count":0,"bff_duplicate_spans":[],"text":"hello world my name is elastic david i am data system engineer want to build real time olap materialized view"}
{"bff_contained_ngram_count":1,"bff_duplicate_spans":[[0,184]],"text":"hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david"}

```

I don't know how to interpret those generated files inside output directory
but I expected duplicates texts to be deleted and only unique texts to be left like

1. test_1.jsonl
```
{"text": "hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david hello world my name is elastic david"}
{"text": "hello world my name is elastic david i am data system engineer want to build real time olap materialized view"}
```

2. test_2.jsonl
```
test_2.jsonl should be empty because test_1.jsonl did already have duplicated two texts
```

But what is like
```
"bff_contained_ngram_count":1,"bff_duplicate_spans":[[0,184]]
```
? 

How can I utilize them to actually deduplicate texts and leave only unique documents only?

**Comment by revbucket** [comment] 2024-09-26 17:36
Hi, 

Thanks for providing an example! 

A few things:
1. Are you sure you're not running this command with the `--annotate` flag? Because if so that would explain your results. When `annotate` is selected, the attribute `bff_duplicate_spans` in the jsonl will tell you which bytes of the text were marked as duplicates and should be removed. Try running without `--annotate` and see if your expected behavior occurs.
2. Based on how parallelism is designed with bff (the bloom filter is shared across threads, but each thread processes files independently), some race conditions _could_ occur where we let some duplicates sneak through because duplicate-ness of a document is checked before the bloom filter is updated. But this is a necessary evil to make the dedup process go fast! 
3. For DCLM, we used a min-ngram, max-ngram of 13,13. This is something we played around with quite a bit and would generally suggest to keep the min/max the same and somewhere in the 13-20 range. YMMV, but this is just what we found :D 

So please try the command w/o annotate, and if everything passes muster, lemme know!

**Comment by ethany21** [comment] 2024-09-27 00:16
@revbucket thnx. I did run command with ```--annotate``` flag. 
And without ```--annotate``` , I got result What I wanted.

**Closed** 2024-10-04 01:18 UTC
